export const midiSongs = [
	{
		title: "Connect",
		artist: "Dial Up",
		url: "/midis/The Sound of dialup Internet.mp3.mid",
	},
	{ title: "Gangsta's Paradise", artist: "Coolio", url: "/midis/Gangsta's-Paradise-1.mid" },
	{
		title: "Cisco Default Hold Music",
		artist: "Unknown",
		url: "/midis/Cisco Default Hold Music HQ Mono Audio Opus Number 1.mp3.mid",
	},
	{ title: "What's My Age Again", artist: "Blink-182", url: "/midis/BLINK182.What's my age again.mid" },
	{ title: "Barbie Girl", artist: "Aqua", url: "/midis/Aqua - Barbie Girl.mid" },
	{ title: "JoJo's Bizarre Adventure Theme", artist: "Unknown", url: "/midis/jojo.mid" },
	{
		title: "Merry Go Round Of Life",
		artist: "Joe Hisaishi",
		url: "/midis/Joe Hisaishi - Merry Go Round Of Life (Howl's Moving Castle).mid",
	},
	{
		title: "A Whole New World",
		artist: "Aladdin Soundtrack",
		url: "/midis/A-Whole-New-World-(Theme-From-'Aladdin').mid",
	},
	{
		title: "Shrek Doot Star",
		artist: "mr skeltal",
		url: "/midis/mr skeltal feat Shrek Doot Star.mp3.mid",
	},
	{
		title: "Age of Empires II Menu",
		artist: "Game Soundtrack",
		url: "/midis/Age of Empires II The Age of Kings - Menu.mid",
	},
	{
		title: "I Want It That Way",
		artist: "Backstreet Boys",
		url: "/midis/Backstreet Boys - I Want It That Way.mid",
	},
	{ title: "Story of a Lonely Guy", artist: "Blink-182", url: "/midis/BLINK182.Story of a lonely guy K.mid" },
	{ title: "Caribbean Blue", artist: "Unknown", url: "/midis/Caribbean-Blue.mid" },
	{ title: "Space Lion", artist: "Cowboy Bebop Soundtrack", url: "/midis/Cowboy Bepop - Space Lion.mid" },
	{ title: "Sandstorm", artist: "Darude", url: "/midis/darude-sandstorm.mid" },
	{
		title: "Kings of the Carnival Creation",
		artist: "Dimmu Borgir",
		url: "/midis/Dimmu Borgir - Kings of the Carnival Creation.mid",
	},
	{ title: "Mr. Blue Sky", artist: "ELO", url: "/midis/ELO - Mr Blue Sky.mid" },
	{ title: "Sweet Dreams", artist: "Eurythmics", url: "/midis/EURYTHMICS.Sweet dreams K.mid" },
	{ title: "Sweet Dreams (Alt)", artist: "Eurythmics", url: "/midis/EURYTHMICS.Sweet dreams K(1).mid" },
	{
		title: "Cruel Angel's Thesis",
		artist: "Evangelion Soundtrack",
		url: "/midis/Evangelion - Cruel Angel's Thesis.mid",
	},
	{ title: "Fur Elise", artist: "Beethoven", url: "/midis/Fur Elise.mid" },
	{
		title: "Merry Go Round Of Life (Alt)",
		artist: "Joe Hisaishi",
		url: "/midis/Joe Hisaishi - Merry Go Round Of Life (Howl's Moving Castle)(1).mid",
	},
	{
		title: "Nuvole Bianche",
		artist: "Ludovico Einaudi",
		url: "/midis/Ludovico Einaudi - Nuvole Bianche.mid",
	},
	{ title: "Billie Jean", artist: "Michael Jackson", url: "/midis/Michael Jackson - Billie Jean.mid" },
	{
		title: "Naruto Main Theme",
		artist: "Naruto Soundtrack",
		url: "/midis/Naruto - Naruto Main Theme-Short Version.mid",
	},
	{
		title: "Pokemon Wild Battle",
		artist: "Pokemon Soundtrack",
		url: "/midis/Pokemon RedBlueYellow - Wild Pokemon Battle.mid",
	},
	{ title: "Bohemian Rhapsody", artist: "Queen", url: "/midis/Queen - Bohemian Rhapsody.mid" },
	{
		title: "Moonlight Densetsu",
		artist: "Sailor Moon Soundtrack",
		url: "/midis/Sailor Moon - Moonlight Densetsu - Moonlight Legend.mid",
	},
	{ title: "Chikyuugi", artist: "Saint Seiya Soundtrack", url: "/midis/Saint Seiya - Chikyuugi.mid" },
	{ title: "The Simpsons Theme", artist: "Unknown", url: "/midis/simpsons-3.mid" },
	{
		title: "Super Mario Bros. Overworld Theme",
		artist: "Nintendo",
		url: "/midis/Super Mario Bros. 1 - Overworld Theme.mid",
	},
	{ title: "Tetris C Theme", artist: "Tetris Soundtrack", url: "/midis/Tetris - C Theme.mid" },
	{ title: "Tetris Main Theme", artist: "Tetris Soundtrack", url: "/midis/Tetris - Tetris Main Theme.mid" },
	{
		title: "Dragonborn Theme",
		artist: "Skyrim Soundtrack",
		url: "/midis/The Elder Scrolls V Skyrim - Dragonborn Theme.mid",
	},
	{
		title: "Dragonborn Theme (Alt)",
		artist: "Skyrim Soundtrack",
		url: "/midis/The Elder Scrolls V Skyrim - Dragonborn Theme(1).mid",
	},
	{ title: "Unravel", artist: "Tokyo Ghoul Soundtrack", url: "/midis/Tokyo Ghoul - Unravel.mid" },
	{ title: "Africa", artist: "Toto", url: "/midis/TOTO.Africa K.mid" },
	{ title: "Mii Channel", artist: "Wii Soundtrack", url: "/midis/Wii Channels - Mii Channel.mid" },
	{
		title: "Great Fairy's Fountain",
		artist: "Zelda Soundtrack",
		url: "/midis/Zelda - Ocarina of Time - Great Fairy's fountain.mid",
	},
	{ title: "Unknown Song 1", artist: "Unknown", url: "/midis/73561_08.mid.mid" },
	{ title: "Unknown Song 2", artist: "Unknown", url: "/midis/112561.mid" },
];
